### PR TITLE
Couple of amendments to my referee report

### PR DESCRIPTION
**Pull request by eggplantbren**

### CODE REVIEW

**Comment by davidwhogg** [comment]
Well that makes it pretty clear who the referee is!

**Comment by davidwhogg** [comment]
ps. @eggplantbren : Thanks for the very constructive comments. Looking forward to discussing more your point -- which is subtle -- about the prior assumptions, the data, and the Gaussian likelihood function.

**Comment by eggplantbren** [comment]
Glad the comments were constructive. I probably should be FIRED for the second round of comments. Happy to discuss philosophy of inference at any time, as you know.

**Comment by adrn** [comment]
@eggplantbren uh oh -- I was too slow! sorry!

**Pull request closed without merging**
